language: python
python:
    - "3.2"
    - "3.3"
    - "3.4"
    - "3.5"
    - "3.6"
    - "pypy"

before_install:
    - sudo apt-get update

install:
    - pip install -r requirements.txt

script:
    - cd examples
    - python ImageRestoration.py
