language: python
python:
    - "2.7"
    - "3.4"
    - "3.5"
    - "3.6"
    - "3.7"

before_install:
    - sudo apt-get update

install: "pip install -r requirements.txt"

script:
    - cd examples
    - python ImageRestoration.py
