language: python
python:
    - "2.6"
    - "2.7"
    - "3.2"
    - "3.3"
    - "3.4"
    - "3.5"
    - "3.6"
    - "3.7"
    - "pypy"

before_install:
    - sudo apt-get update

install:
    - pip install -r requirements.txt

virtualenv:
    system_site_packages: true

script:
    - cd examples
    - python ImageRestoration.py
