language: python
python:
    - "3.3"
    - "3.5"
    - "3.4"
    - "3.6"
    - "3.7-dev"
# command to install dependencies
install:
    - pip install numpy
    - pip install numba
# command to run tests
script:
    - examples/ImageRestoration
