language: python
python:
    - "2.7"
    - "3.5"
    - "3.6"

before_install:
    - sudo apt-get update

install: "pip install -r requirements.txt"

script:
    - curl -L https://github.com/Zeroto521/DHNN/archive/master.zip
    - unzip master.zip
    - cd master
    - python setup.py install
    - cd examples
    - python ImageRestoration.py
